main:
  - name: About
    url: '#about'
    weight: 10
  - name: Speakers
    url: '#speakers'
    weight: 20
  - name: Schedule
    url: '#schedule'
    weight: 30
  - name: Registration
    url: '#tickets'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 70

